# Exceptions


In programming, exceptions are problems that can occur during the execution of a program. In Python, exceptions are designed as special objects that can be "raised" and "caught". When an exception is raised, the program flow will immediately transfer to the nearest exception handler that can handle that exception. If no corresponding handler is found, the program will terminate and display the exception message.




## Handling Exceptions

We can use `try..except` statements to catch exceptions. The `try` statement contains the block of code that may raise an exception, as well as the exception handlers that handle those exceptions. The `except` block contains all the error handlers.  

The basic syntax of a `try..except` statement is:  

```{python}
try:
    # Code that may raise exception
    x = 1 / 0  
except ZeroDivisionError:
    print("Cannot divide by zero")
```

In the above code example:

- The `try` statement contains code that may raise an exception, i.e. `x = 1 / 0`.  
- The `except` statement contains the code to handle exceptions, i.e. `print("Cannot divide by zero")`.
- The `except` statement can handle a single specified exception or a tuple of exceptions inside parentheses.  
- If no exception type is specified, the `except` statement will catch all types of exceptions.
- In the code sample, `except ZeroDivisionError` specifies to only catch `ZeroDivisionError` exceptions. This is a specific exception type for handling divide by zero errors.
- Each `try` statement can have multiple `except` statements to handle different types of exceptions. However, only one `except` statement will be executed.  
- Each `try` statement must have at least one `except` statement or `finally` statement to handle exceptions.


### The `else` Statement  

The `else` statement is used to specify a block of code to execute if no exception occurs. The basic syntax of the `else` statement is:

```{python}
try:
    # Code that may raise exception  
    x = 1 / 1   
except ZeroDivisionError:
    print("Cannot divide by zero")
else:
    # Code to execute if no exception occurs
    print("No exceptions occurred") 
```

In the above code example:

- The `else` statement contains code to execute if no exception occurs, i.e. `print("No exceptions occurred")`.
- The `else` statement is usually used to perform some clean-up operations when no exception occurs.
- The `else` statement must appear after all `except` statements but before the `finally` statement.


### The `finally` Statement

The `finally` statement is used to specify a block of code to execute regardless of whether an exception occurs or not. The `finally` statement is usually used to release resources or perform clean-up operations. The basic syntax of the `finally` statement is:  

```{python}

try:
    # Code that may raise exception
    x = 1 / 0   
except ZeroDivisionError:
    print("Cannot divide by zero")  
else:
    # Code to execute if no exception occurs
    print("No exceptions occurred")
finally:
    # Code to execute regardless of exception 
    print("This is always executed")
```

In the above code example:  

- The `finally` statement contains code to always execute regardless if an exception occurs or not, i.e. `print("This is always executed")`.
- The `finally` statement is usually used to release resources or perform clean-up operations. For example, we can close files, release locks, close database connections etc. in a `finally` statement.


### The `with` Statement  

In Python, the `with` statement is syntactic sugar that is mainly used to simplify resource management related code. For resources like file operations, network connections, database connections etc. that require explicit release after use, we can use the `with` statement to automatically manage the release of resources, making the code more concise and avoiding potential resource leaks.


::: {.callout-tip}
# What is Syntactic Sugar  

Syntactic sugar refers to syntax designed to make certain programming tasks easier to read or more expressive. Its main purpose is to improve readability of programs, make code more concise, or make semantics more explicit.  

The term "syntactic sugar" was originally coined by Peter J. Landin (a computer scientist) in 1964, and is used figuratively to describe features that don't add new functionality to a computer language but make it more pleasant for humans to write or read code.  

The figurative meaning of this noun is that such syntax is like adding some "sugar" to code, making the code that may otherwise be dull and rigid become sweeter and more aesthetic, bringing fun to programming. Just like sugar improves the taste of food without adding nutrition, syntactic sugar makes code more pleasant and easier to understand without changing the core functionality or semantics of the programming language.  

For example, decorators and list comprehensions in Python don't add any new functionality to the language, they just make it clearer to write code with the same functionality, making programming more enjoyable. So they are called "syntactic sugar".
:::


The basic syntax of a `with` statement is:  

```python
with expression as variable:
    # code block
```

Where `expression` must be an object that implements the `__enter__` and `__exit__` methods.  

- The `__enter__` method is invoked before executing the code block, used to return a resource object.
- The `__exit__` method is invoked after finishing executing the code block, responsible for cleaning up or releasing resources.


An example of using a `with` statement is:  

```python
with open(r"practical_code\input_and_output\data.pkl", "wb") as f:
    pickle.dump(data, f) 
```

In the above code example:  

- The `with` statement first invokes the `__enter__` method of the file object to open the file, and then assigns the returned file object to `f`.
- Next, the `with` statement executes the code block, i.e. `pickle.dump(data, f)`.  
- Regardless if this code block raises exceptions or not, the `with` statement invokes the `__exit__` method of the file object to close the file. So we don't need to explicitly call `f.close()` to close the file.  

When handling exceptions without using `with` statements, we would need to explicitly call `f.close()` in a `finally` statement of the `try` block to close the file. By using `with` statements, we don't need to do this.

## Exception Classes  

Python provides some built-in exception classes to represent different types of error conditions. Common exception classes include:  

- `Exception`: Base class for all exception classes.  
- `NameError`: Name error, raised when trying to access a variable or function that does not exist.
- `TypeError`: Type error, raised when an operation or function is applied to an incompatible type.   
- `ValueError`: Value error, raised when an operation or function is applied to an object with the correct type but invalid value.  
- `IndexError`: Index error, raised when trying to access an index of a list, tuple or string that does not exist.  
- `KeyError`: Key error, raised when trying to access a key in a dictionary that does not exist.   
- `FileNotFoundError`: File not found error, raised when trying to open a file that does not exist.


## Raising Exceptions  

We can use the `raise` statement to raise exceptions. The `raise` statement is used to raise a specified exception.  

The exception that can be raised can be an instance of any class, but is usually an instance of built-in exception classes. The basic syntax of a `raise` statement is:  

```python
raise ValueError("Invalid value") 
```
This line of code raises a `ValueError` exception with the error message `Invalid value`. In general, we raise exceptions this way to notify callers that some specific error condition has occurred, and we can define custom exception classes for such cases.

## Custom Exception Classes  

A custom exception class is a class that inherits from the `Exception` class. We can create custom exception classes by inheriting from the `Exception` class. The basic syntax of a custom exception class is:   

```python
class ShortInputException(Exception):
    def __init__(self, length, atleast):
        self.length = length
        self.atleast = atleast
try:
    text = input("Enter something --> ")
    if len(text) < 3:
        raise ShortInputException(len(text), 3)  
except EOFError:
    print("Why did you do an EOF on me?")
except ShortInputException as e:
    #print("ShortInputException: The input was of length %d, was expecting at least %d" % (e.length, e.atleast))
    print(f"ShortInputException: The input was of length {e.length}, was expecting at least {e.atleast}")
else:
    print("No exception was raised")
```

In the above code example:  

- `ShortInputException` is a custom exception class that inherits from the `Exception` class.
- The statement `raise ShortInputException(len(text), 3)` raises a `ShortInputException` exception.  
- When an `except` statement catches an exception, it generates an exception instance containing the details. We can use the `as` keyword to assign the instance a variable name that we can then access in the except block for the exception details.
- `%d` is a placeholder for formatting strings. The `%` operator is used for string formatting. In this case, `%d` indicates inserting an integer into the string.  
- In Python 3.6 and later, we can use f-strings for string formatting. F-strings provide a new way to format strings where variables can be directly inserted using variable names instead of placeholders, making it more intuitive and flexible.